### ISSUE TITLE
docker image update

### ISSUE THREAD

**Issue by fopina** [Stremio/stremio-service#48]
It looks like https://hub.docker.com/r/stremio/server is still using some server.JS version not this rust package.

Is there a plan to update it or is it a different package?

**Comment by jaruba** [comment]
Stremio Service is a Rust wrapper around the server, the Docker image is a different wrapper around the server, the Docker image thus does not need Rust at all.

**Comment by fopina** [comment]
Makes perfect sense, thought this was a refactor in rust from an older JS implementation 👌

**Comment by jaruba** [comment]
it is not a refactor in rust, check this comment here: https://github.com/Stremio/stremio-service/blob/a7be81eb6175f732f7c8a7284ec62ff62945b34c/build.rs#L14
