### ISSUE TITLE
RPM package binary location

### ISSUE THREAD

**Issue by onurmercury** [Stremio/stremio-service#52]
Unlike DEB package, binaries needed by stremio-service appear under /usr/bin/stremio-service/bin/ , not /usr/bin/stremio-service/ . Moving binaries to /usr/bin/stremio-service/ fixes the problem.

```
Error: Server.js configuration failed

Caused by:
    One or more binaries were not found; paths: /usr/bin/stremio-service/node; /usr/bin/stremio-service/ffmpeg; /usr/bin/stremio-service/ffprobe; /usr/bin/stremio-service/server.js; Errors: [ffprobe not found at: /usr/bin/stremio-service/server.js, server.js not found at: /usr/bin/stremio-service/server.js]
```

**Comment by RDKRACZ** [comment]
I also have this issue and can confirm the workaround is working.

**Comment by tymmesyde** [comment]
It has been fixed but the release is not published yet

**Comment by onurmercury** [comment]
> It has been fixed but the release is not published yet You can download it here: https://github.com/Stremio/stremio-service/releases/tag/v0.1.8

Yes, I forgot to close the issue. Thanks.
