### ISSUE TITLE
Cannot connect stremio web running on LG TV's web browser to stremio service running on Macbook Pro

### ISSUE THREAD

**Issue by duyhoan** [Stremio/stremio-service#70]
Hi guys,

I'm trying to find a way to use stremio web with stremio service for accessing stremio on LG TV web browser. Here is my setup:
- I download and run the stremio service on my Macbook Pro
- I observe the local IP address of my Macbook via Network setting in System Preferences: Network -> Wifi -> Details on connected wifi -> TCP/IP -> IP Address
- I open [web.stremio.com](https://web.stremio.com/) on LG TV's web browser, log in and go to Settings -> Streaming
- I modify the Url configuration there and set it to be like this: http://{my_Macbook_local_IP_address}:11470

However, it keeps indicating the Server Error, which means that it cannot connect to the stremio service that is running on my Macbook. I already ensured that both of my Macbook and LG TV is connecting to the same Wifi network. Which step I'm missing here? Or how can I adapt LG TV / my Macbook network setting / my router to make it work?

Further information about the system hardware:
- My Macbook Pro is running on MacOS ventura with Apple M2 chip
- My LG TV is LG C3 evo, 2023 model. WebOS version is 03.30 I believe.

**Comment by TRtomasz** [comment]
there is no need to open same issue in multiple repositories
