### ISSUE TITLE
[Question] for Devs and Community

### ISSUE THREAD

**Issue by DaddyBoard** [Stremio/stremio-service#75]
Tesla's browser doesnt allow any non-SSL connections whatsoever, I can navigate to the web.stremio.com etc, set the streaming server, but it says "Error" even though the same link works fine on my iOS browser. 

is there any way I can setup the Stremio service to have an SSL cert of some kind to be allowed in Tesla's browser?

**Comment by jaruba** [comment]
Stremio only gives free SSL certificates for LAN use, and exposing the service to the internet is not recommended by our team.

So if you want to do that, you will have to handle it yourself, maybe by buying a domain first, then using stremio server docker, proxying it through NGINX, getting an SSL cert for the domain (maybe from Let's Encrypt), then configuring the SSL cert in NGINX. We cannot offer a guide for this, but it is possible.
